### ISSUE TITLE
Ajout de cartes de communication

### ISSUE THREAD

**Issue by totchi-lagawi** [Eliyaan/DDR-documentation#1]
Bien que les solutions actuellement citées soient les plus simples d'utilisation, il pourrait être intéressant d'également lister quelques cartes permettant l'émulation d'un clavier. Je noterais bien évidemment l'Arduino, tant qu'elle possède une interface USB-A, mais également la carte Makey Makey, semblable à l'USB Arcade Encoder déjà présent.

**Comment by Eliyaan** [comment]
Je ne sais pas comment faire que l'Arduino simule une clavier, de même pour le Makey Makey, c'est pour ca que je ne les ai pas mises surtout. (et qu'elles sont plus couteuses)

**Comment by totchi-lagawi** [comment]
Pour l'Arduino, il existe une librarie HID le permettant. Makey Makey est conçue pour simuler un clavier, donc pas de problème de ce côté. Je me doute bien qu'elles sont plus chères, cependant il serait je pense bien de les citer dans la documentation, même si elle se concentre sur l'USB Arcade Encoder.

**Comment by Eliyaan** [comment]
Okay, je vais l'ajouter
