### ISSUE TITLE
à propos de votre projet / magazine programmez

### ISSUE THREAD

**Issue by francoistonic** [Eliyaan/DDR-documentation#2]
bonjour,

je viens de découvrir votre projet DIY, énorme ! et super intéressant. nous préparons à programmez! un dossier sur aborder simplement le côté programmation et maker pour notre numéro de janvier.

ce projet serait parfait pour ce dossier !

mon mail : ftonic@programmez.com

**Comment by Eliyaan** [comment]
Je vous ai contacté par mail. Merci de votre intéret pour le projet !
